-- Do Not Edit This File.
-- [32] = default; [33] = line number; [34] = brace highlight; [35] = unmatched brace
return {
	common = {
		style = {
			caret = {
				back = "#3a3a3a"
			},
			comment = {
				bold = true,
				fore = "#92ff2c",
				italic = true
			},
			docComment = {
				fore = "#993300",
				italic = true
			},
			docKeyword = {
				bold = true,
				fore = "#663300",
				italic = true
			},
			doubleQuotedString = {
				fore = "#209e1f"
			},
			error = {
				back = "#ff0000",
				eolfilled = true,
				fore = "#ffff00"
			},
			find = {
				back = "#fc1216"
			},
			foldMargin = {
				back = "#262626"
			},
			identifier = {

			},
			inactive = {
				back = "#450505",
				eolfilled = true
			},
			keyword = {
				bold = true,
				fore = "#9e00ff"
			},
			label = {
				fore = "#800000"
			},
			number = {
				fore = "#00d0d0"
			},
			operator = {
				bold = true
			},
			preprocessor = {
				bold = true,
				fore = "#dbc900"
			},
			ref = {
				back = "#92ff2c"
			},
			selection = {
				back = "#4d4d4d"
			},
			singleQuotedString = {
				fore = "#41aa11"
			},
			unclosedDoubleQuotedString = {
				back = "#800000",
				eolfilled = true
			},
			unclosedSingleQuotedString = {
				back = "#800000",
				eolfilled = true
			},
			whitespace = {
				fore = "#808080"
			}
		}
	},
	style = {
		[32] = {
			back = "#1d1d1d",
			fore = "#e3e3e3"
		},
		[33] = {
			back = "#a0a0a0",
			fore = "#cfcb64"
		},
		[34] = {
			back = "#006100",
			bold = true,
			fore = "#bababa"
		},
		[35] = {
			back = "#8a0000",
			bold = true,
			fore = "#bababa"
		}
	},
	udb = {
		style = {
			ada = {
				globalVariableNames = {
					bold = true,
					fore = "#ff55ff",
					underline = true
				},
				localVariableNames = {
					fore = "#ff55ff",
					italic = true
				},
				packageNames = {
					fore = "#ff5500"
				},
				subprogramNames = {
					fore = "#ffaa00"
				}
			},
			cs = {
				classNames = {
					fore = "#ff5500"
				},
				methodNames = {
					fore = "#ffaa00"
				}
			},
			cxx = {
				classNames = {
					fore = "#ef00ff"
				},
				enumeratorNames = {
					fore = "#e01112"
				},
				functionNames = {
					fore = "#fff90d"
				},
				globalVariableNames = {
					bold = true,
					fore = "#d60010"
				},
				localVariableNames = {
					fore = "#f2ffff"
				},
				macroNames = {
					fore = "#e00017"
				},
				memberFunctionNames = {
					fore = "#fffc10"
				},
				memberVariableNames = {
					fore = "#2af8ff"
				},
				namespaceNames = {
					fore = "#fc2bff"
				},
				parameterNames = {
					fore = "#1471ff"
				},
				typeNames = {
					fore = "#e800ff"
				},
				virtualFunctionNames = {
					fore = "#fffc10"
				}
			},
			fortran = {
				subprogramNames = {
					fore = "#ffaa00"
				}
			},
			java = {
				classNames = {
					fore = "#ff5500"
				},
				methodNames = {
					fore = "#ffaa00"
				}
			},
			jovial = {
				subroutineNames = {
					fore = "#ffaa00"
				}
			},
			pascal = {
				routineNames = {
					fore = "#ffaa00"
				}
			},
			python = {
				classNames = {
					fore = "#ff5500"
				},
				functionNames = {
					fore = "#ffaa00"
				}
			},
			vhdl = {
				subprogramNames = {
					fore = "#ffaa00"
				}
			}
		}
	}
}