# Header
# Github link:
# https://github.com/litten/hexo-theme-yilia

menu:
  Home: /
  SomeThing: /tags/SomeThing/

# SubNav
subnav:
  github: "https://github.com/riccoqu"
  zhihu: "https://www.zhihu.com/people/qu-rui-kang/activities"
  weixin: "http://7xrxgj.com1.z0.glb.clouddn.com/Blog/Images/AddMeOnWecht.jpg"
  mail: "mailto:ricco.qu@outlook.com"
  #weibo: "#"
  #qq: "#"
  #rss: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

root: /

# Content
# 文章太长，截断按钮文字
excerpt_link: false
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: 'More'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 1
reward_wording: 'Wish you a good day'
alipay: /images/AliPay.jpg
weixin: /images/WeChatPay.jpg

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 2
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: 'directory is empty'
# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: /images/Avatar.jpg

#是否开启分享
share_jia: true

# 多说
duoshuo: false
# 网易云跟帖
wangyiyun: false
# 畅言
changyan_appid: false
changyan_conf: false
# Disqus
disqus: false
# Gitment
gitment_owner: false      #你的 GitHub ID
gitment_repo: ''          #存储评论的 repo
gitment_oauth:
  client_id: ''           #client ID
  client_secret: ''       #client secret

style:
  header: '#4d4d4d'
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

slider:
  showTags: true

smart_menu:
  innerArchive: 'All Archive'
  aboutme: 'aboutme'

friends:

aboutme : thankyou
